name: "Terraform for R53 DNS hosted zones and records"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "hosted_zones/dsd.io"
    branches:
      - main
  push:
    paths:
      - "hosted_zones/dsd.io"
    branches: [ "main" ]

env:
  TERRAFORM_VERSION: "1.7.5"

jobs:
  terraform:
    name: "Terraform DNS"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    defaults:
      run:
        working-directory: "hosted_zones/dsd.io"
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Configure AWS Credentials for Infra Account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_DSD_CICD_ADMIN_ROLE_ARN }}
        aws-region: eu-west-2
        
    - name: Terraform Init
      id: init
      run: ls -latr; terraform init -input=false -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -no-color

    - name: Terraform Apply
      # if: github.ref == 'refs/heads/main'
      id: apply
      run: terraform apply -input=false -no-color -auto-approve